spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-52-206-14-156.compute-1.amazonaws.com/ddt3s46rvvqovh
  username: mqkgztfmeuausj
  password: 8b94076ee6e241fe4564e9f895bc9bbd03de017564a5c9278df494c28738dda5
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  token.expired-time-ms: 2592000000   # 30 days

